name: Changeset Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/setup

      - name: Create Release Pull Request or Publish to GitHub
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun run changeset-version
          commit: "chore: release packages"
          title: "chore: release packages"
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if version was updated
        id: version-updated
        run: |
          if [[ "${{ steps.changesets.outputs.hasChangesets }}" == "false" && "${{ steps.changesets.outputs.pullRequestNumber }}" == "" ]]; then
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      - name: Get current version
        if: steps.version-updated.outputs.updated == 'true'
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Check if release exists
        if: steps.version-updated.outputs.updated == 'true'
        id: release-exists
        run: |
          if gh release view "v${{ steps.package-version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create single file executable
        if: steps.version-updated.outputs.updated == 'true' && steps.release-exists.outputs.exists == 'false'
        run: bun build --compile --outfile=todo-cli ./src/bin.ts

      - name: Create GitHub release with executable
        if: steps.version-updated.outputs.updated == 'true' && steps.release-exists.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            todo-cli
          tag_name: v${{ steps.package-version.outputs.version }}
          name: v${{ steps.package-version.outputs.version }}
          body: |
            Release v${{ steps.package-version.outputs.version }}
            
            Download the `todo-cli` executable from the assets below.
            
            See [CHANGELOG.md](https://github.com/MichaelVessia/todo-cli/blob/master/CHANGELOG.md) for detailed changes.
          draft: false
          prerelease: false