name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Build package
        run: bun run build
      - name: Create single file executable
        run: bun build --compile --outfile=todo-cli ./src/bin.ts
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            todo-cli
          draft: false
          prerelease: false