name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/setup

      - name: Build package
        run: bun run build

      - name: Run tests
        run: bun test

      - name: Get current version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: tag-exists
        run: |
          if git show-ref --tags --quiet --verify -- "refs/tags/v${{ steps.package-version.outputs.version }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create single file executable
        if: steps.tag-exists.outputs.exists == 'false'
        run: bun build --compile --outfile=todo-cli ./src/bin.ts

      - name: Create GitHub release
        if: steps.tag-exists.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            todo-cli
          tag_name: v${{ steps.package-version.outputs.version }}
          name: v${{ steps.package-version.outputs.version }}
          body: |
            Release v${{ steps.package-version.outputs.version }}
            
            Download the `todo-cli` executable from the assets below.
          draft: false
          prerelease: false